config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  devise_for :users

  namespace :admin do
    get 'dashboard', to: 'dashboard#index'
    resources :genres
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/genre.rb
class Genre < ApplicationRecord
  # Жанр имеет опорную таблицу "жанры-фильмы"
  has_many :genre_movies

  # Жанр имеет много фильмов
  has_many :movies, through: :genre_movies

  # Название жанра обязательно и не может дублироваться
  validates :name, presence: true, uniqueness: true
end

app/models/genre_movie.rb
class GenreMovie < ApplicationRecord
  belongs_to :genre
  belongs_to :movie
end

app/models/hall.rb
class Hall < ApplicationRecord
  # Зал имеет множество слотов рассписания
  has_many :timeslots

  # Зал имеет множество фильмов через связь слотов рассписаний
  has_many :movies, through: :timeslots

  # Название зала обязательно и должно быть уникальным
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  # Фильм имеет опорную таблицу
  has_many :genre_movies

  # Фильм имеет множество жанров
  has_many :genres, through: :genre_movies

  # Фильм имеет множество слотов в рассписании
  has_many :timeslots

  # Валидация обязательных арртибутов
  validates :name, :name_ru, :description, :min_age, :duration_min, :rating, presence: true
end

app/models/timeslot.rb
class Timeslot < ApplicationRecord
  # Слот пренадлежит фильму
  belongs_to :movie

  # Слот пренадлежит залу
  belongs_to :hall

  # Валидация обязательных аттрибутов
  validates :start_time, :end_time, :hall, :movie, presence: true

  # Валидация слота времени
  validate do |record|
    if record.start_time >= record.end_time
      errors.add(:base, 'Start time can not be greater than or equal to End time')
    end

    if record.end_time <= record.start_time
      errors.add(:base, 'End time can not be less than or equal to Start time')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/dashboard_controller.rb
module Admin
  class DashboardController < ApplicationController
    layout 'admin'

    before_action :authenticate_user!

    def index

    end
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_user!
  layout 'admin'

  def index
    @genres = Genre.all
  end

  def edit
    @genre = find_genre
  end

  def create
    @genre = Genre.new
    if @genre.update(genre_params)
      flash.notice = 'Success'
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  def update
    @genre = find_genre

    if @genre.update(genre_params)
      flash.notice = 'Success'
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  def destroy
    @genre = find_genre
    if @genre.movies.count > 0
      flash[:alert] = 'Удаление невозможно: Имеются фильмы с данным жанром'
      return redirect_to admin_genres_path
    end

    if @genre.destroy
      flash[:alert] = "Жанр #{@genre.name} Удален"
      redirect_to admin_genres_path
    end
  end

  def new
    @genre = Genre.new
  end

  private

  def find_genre
    Genre.find(params[:id])
  end

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/genres/edit.html.erb
<%= simple_form_for @genre, url: admin_genre_path(@genre) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/admin/genres/index.html.erb
<div class="row">
  <div class="col">
  </div>
  <div class="col-auto">
    <%= link_to 'Добавить', new_admin_genre_path, class: 'btn btn-primary ' %>
  </div>
</div>
<hr>

<table class="table">
  <thead>
    <tr>
      <td>Название</td>
      <td>Кол-во фильмов</td>
      <td>Действия</td>
    </tr>
  </thead>

  <tbody>
    <% @genres.each do |genre| %>
      <tr>
        <td><%= genre.name %></td>
        <td><%= genre.movies.count %></td>
        <td>
          <div class="row">
            <div class="col-3">
              <%= link_to 'Редактировать', edit_admin_genre_path(genre), class: 'btn btn-primary' %>
            </div>
            <div class="col-3">
              <%= button_to 'Удалить', admin_genre_path(genre), method: :delete, class: 'btn btn-danger' %>
            </div>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/admin/genres/new.html.erb
<%= simple_form_for @genre, url: admin_genres_path do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin::Dashboard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Администратор</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Конфигурация
              </a>
              <ul class="dropdown-menu dropdown-menu-dark">
                <li><%= link_to 'Жанры', admin_genres_path, class: 'dropdown-item' %></li>
                <li><a class="dropdown-item" href="#">Рассписание</a></li>
              </ul>
            </li>
          </ul>
        </div>
        <div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown1" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDarkDropdown1">
            <ul class="navbar-nav">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Аккаунт
                </a>
                <ul class="dropdown-menu dropdown-menu-dark">
                  <li class="nav-item">
                    <%= link_to 'Выйти', destroy_user_session_path, class: 'nav-link', data: { "turbo-method": :delete } %>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </nav>
    <div class="container">
      <% if flash[:notice] %>
        <%= flash[:notice] %>
      <% end %>

      <% if flash[:alert] %>
        <%= flash[:alert] %>
      <% end %>

      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JbnuuCourseWork1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<%= link_to 'Панель администратора', admin_dashboard_path %>